
export const SELECT_MENU = 'SELECT_MENU'
export const TOGGLE_AUTOPILOT = 'TOGGLE_AUTOPILOT'
export const SELECT_DRIVE_STATUS = 'SELECT_DRIVE_STATUS'
export const CHANGE_DRIVE_STATUS = 'CHANGE_DRIVE_STATUS'